### ISSUE TITLE
 Add an option to exclude matches in the ‘References’ section

### ISSUE THREAD

**Issue by sjm41** [alliance-genome/agr_textpresso#25]
It would be helpful if there was an option to exclude matches in the ‘References’ section - such matches are usually not relevant. I'd make the default behaviour to exclude these, and allow the user to change this if they really wanted them.

**Comment by sjm41** [comment]
To clarify this request:
When you do a search, you can set the ’search location’ to be the default ‘document’ or change this to be any of the subsections (e.g. ‘abstract', or ‘results’). What you can’t seem to do right now is **exclude** specific subsections from the search results. E.g. it would be especially useful to be able to **exclude** hits from the ‘References’ subsection to avoid false positive hits just to keywords present only in other papers listed in the reference section.

**Comment by cerivs** [comment]
In Jira https://agr-jira.atlassian.net/browse/KANBAN-577
